# Generated by Django 3.2.4 on 2021-06-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='caroussel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/image/')),
                ('title', models.CharField(max_length=250)),
                ('sub_title', models.CharField(max_length=100)),
            ],
        ),
    ]
