# Generated by Django 3.2.4 on 2021-06-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corp', '0002_caroussel'),
    ]

    operations = [
        migrations.CreateModel(
            name='carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/img/')),
                ('title', models.CharField(max_length=250)),
                ('sub_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='caroussel',
        ),
    ]
