# Generated by Django 3.2.4 on 2021-06-21 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corp', '0004_auto_20210617_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='occurrence',
            name='event',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventType',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='Occurrence',
        ),
    ]
